### ISSUE TITLE
pm.conversation.count

### ISSUE THREAD

**Issue by copleykj** [StorytellerCZ/meteor-messaging-server#1]
Just wanted to open up a discussion about this.. Look at this I wonder if the message count should be a field on the conversation document that gets incremented when a message is added, and decremented when a message is removed.

Thoughts?

**Comment by StorytellerCZ** [comment]
Well that goes into the entire discussion about counting entries in the DB. On lower count of documents it is not an issue, but with higher counts if not done efficiently (indexes, etc.) it can have impact on the speed of DB as it needs to get through more documents.
My implementation uses this to get the total of messages so that I can determine if I should show the "show older messages" button to adjust the limit for the conversation.

As for having it as a field on the conversation document... I think it would be nice, given that adjusting the total would be automated in the messaging package. Otherwise it would make sense only to large projects to implement this as smaller projects don't need to worry that much about performance.
